### ISSUE TITLE
Code & app

### ISSUE THREAD

**Issue by johancvb** [dewarian/real-time-web-2021#11]
Je code ziet er strak uit, je gebruikt duidelijke variabelnamen, en codeert heel consistent; Dit is voor de lezer heel fijn en overzichtelijk. Op je coding-style heb ik dus niks op aan te merken.

Je app mist duidelijk nog de styling, en heeft ook nog een kleine ?bug?. Als je een nieuw document aanmaakt, hier wat in schrijft, en het daarna wilt opslaan, ga je niet gelijk terug naar de homescreen. Dus weet je als gebruiker niet of je document daadwerkelijk is opgeslagen. Misschien is het een idee om een soort bevestiging te geven als het document is opgeslagen, of dat je terug naar de homepage gaat als je op "Save" klikt. Ik weet niet of dit misschien de bedoeling was, maar het is misschien fijner voor de gebruiker om wat feedback te krijgen of het bestand is opgeslagen. 

--Johan

**Comment by bommezijn** [comment]
Hoi Hoi,

Dankjewel voor de feedback. Issue heb ik verwerkt in 67f943f9da25d4d0b845bc2126f760b71e0ac664 en 8292745046d84357b9858293f1cb0ae91fa72983.

Opslaan stuurt nu de gebruiker terug naar de homepagina.
