### ISSUE TITLE
Feedback week 2

### ISSUE THREAD

**Issue by johancvb** [dewarian/real-time-web-2021#3]
## Repo:

Super gedetailleerde ReadMe, heel duidelijk en overzichtelijk om te lezen. Bevat een live link naar de demo. Alles wordt duidelijk en uitgebreid uitgelegd, zoals het concept van de webapp, hoe te installeren, en alle functies van de app. Alles wordt goed ondersteund door duidelijke Data Flows en class diagrams. Niks op te merken aan de ReadMe dus :) 

## App:

De webapp is een chat app, waarmee je met verschillende gebruikers kunt chatten. De app mist alleen nog veel van de in de ReadMe geschreven functies. Het is misschien handiger voor de gebruiker om te zien wie welk bericht heeft gestuurd, en wie er allemaal online zijn in de chat. Ik denk dat je dat ook van plan was, maar je er nog niet aan bent gekomen. Voor de rest is het nu nog een basic webapp qua styling, maar ook daar zal je vast nog wat aan doen.

## Code:

Je serversided code is duidelijk, nog basic, maar wel functioneel. Het stuurt de berichten van de gebruikers door naar de verschillende clients, dus dat werkt goed. Ook zie ik dat je gebruik maakt van een database, wat erg handig is voor het opslaan van de gebruikers. Deze code ziet er ook strak en overzichtelijk uit, en komt overeen met de class diagram van je ReadMe.

Ik zie in je code dat je ook gebruik maakt van firestore. Ik heb hier zelf nog nooit van gehoord/ mee gewerkt, maar ook dit wordt uitgelegd in je ReadMe.

Overall, je code ziet er goed uit, je ReadMe is echt super gedetailleerd, alleen de functies van de WebApp zijn nog minimaal, maar ik denk dat je daar nog volop mee bezig bent 😉

-- Johan

**Comment by bommezijn** [comment]
Refer to issue #6 to track progress.

Closing this issue.
