### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by HappyPantss** [dewarian/real-time-web-2021#4]
Hey Nathan!

In this review I'll tell you what you miss from the rubric/ peer review sheet.

* You're README has obviously a description, but I would consider changing your description in your 'About' (on top of your repo)
* There's no data about how to install your app and information about your external api

* TOP: It's cool that the multi-user functionality already works!

* I don't see your custom events described

* As already told, there is no information about your API.
* If you write this, think about how instructions on how to get a key from the API and how to connect it. So all users can use it

Overall, your repo looks good and the concept is really cool

~ Keep coding

**Comment by bommezijn** [comment]
Hi, 

Thank you for the feedback. I will change the description.

About the installation, It is mentioned under [technicalities](https://github.com/dewarian/real-time-web-2021#installation) but will mention it more explicitly.

About the API, Considering the nature of the application there will be no API used in this project.
But thanks for the feedback about also explicitly mentioned how a user can obtain a key from the API.

**Comment by bommezijn** [comment]
Reference to issue #6 to track progress about socket events.

Closing this issue.
