### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by ofahchouch-gh** [dewarian/real-time-web-2021#5]
De repo is goed beschreven, je bent goed bezig met je readme. Je hebt verder niet de node modules mee gepushed en deze in je git ignore gezet wat goed is. Je maakt al gebruik van een productie omgeving en pushed je nieuwste features er naartoe wat goed is. Verder heb je een een prima data-flow diagram gemaakt. 

Je hebt een leuk concept bedacht, en legt uit hoe de app werkt middels de tekeningen. Goed dat je ook verschillende concepten hebt. Deze zijn ook redelijk uitgebreid getekend, je hebt dus je tijd er in gestoken. Ook leuk dat je bezig bent met conventions, een data model hebt gemaakt. Verder mist er nog wel wat, maar dat weet je vast zelf ook, geen beschrijving van de socket events en geen omschrijving voor de installatie.

Nog een tip over de code. Probeer met modules te werken, dat gebeurd straks alleen maar op stage/werk. Je kan een service gebruiken voor je database logica en een persistence laag voor de logica gerelateerde aan een entiteit in je database. En met bijvoorbeeld controllers en services kan je applicatie en domein logica afhandelen.

**Comment by bommezijn** [comment]
Hi,

Dankjewel voor de feedback. Ik moet inderdaad nog aan de slag om er een MVP van te maken.
Voor de punten die nog niet zichtbaar waren zal ik deze in de volgende issues oplossen.

De tip zal ik zeker gebruiken. Dat was de intentie ook van dit project.

**Comment by bommezijn** [comment]
Reference to issue #6 to track progress.

Closing this issue.
