### ISSUE TITLE
scanning the repo

### ISSUE THREAD

**Issue by ofahchouch-gh** [dewarian/real-time-web-2021#8]
Je bent heel goed bezig met het documenteren van je opdrachten, dat merk ik ook in andere projecten. Ga zo door :)! Je repo heeft een duidelijke beschrijving van je idee en je hebt een link naar een live omgeving. Verder zijn er geen files te vinden die er niet in horen zoals een .env of node_modules. Je hebt ook een stukje voor de install notes en beschrijft je npm scripts goed. Daarnaast heb je een duidelijk data life cycle diagram en heb je het ook over je externe API (ik gebruik er btw geen, voor als je mij gaat reviewen daarover). Vergeet niet de real-time events te beschrijven :)!

**Comment by bommezijn** [comment]
Hoi Hoi, 

Dankjewel voor de feedback. Ik heb de documentatie verwerkt naar aanvang van jouw feedback. Zie issues voor veranderingen.

|issue|beschrijving|
|:--|:--|
|851f6ba9c47bb95ddf6d67f6ae221fc2d653abd1|Events verwerkt in de readme|
|3388fc69338a17cb05cdbeb12a2959fda3ec72a1| socket.io events verwerkt in eigen module|
