### ISSUE TITLE
over de code

### ISSUE THREAD

**Issue by ofahchouch-gh** [dewarian/real-time-web-2021#9]
Goed dat je bezig bent met het modulair maken van je app! Je gebruikt ook models en services, heel goed. 

Je kan verder gaan,  je database service zou je alleen voor je database connecties kunnen gebruiken. Ik zie dat je daar een insertUserDb (data) in hebt staan, deze zou je kunnen verplaatsen naar een persistence laag en bijvoorbeeld in een class stoppen met de naam UserPersistence. Zo houdt je de service laag en persistence laag gescheiden. Die userConverter kan in een mapper laag en hoeft niet persee in de UserPersistence. Misschien wist je dit al, het is vooral handig bij grotere projecten.

**Comment by bommezijn** [comment]
Hoi Hoi,

Dankjewel voor de feedback. De Mapper laag voor mij niet een bekende laag maar ik zal er onderzoek naar doen.
Door de omvang van de applicatie zal ik dit niet verder verwerken in verschillende lagen.
